using SCIQUSTICKETS.BUSINESS.BusinessModels.RequestDTOs.AccountRequestDTOs;
using SCIQUSTICKETS.BUSINESS.BusinessModels.ResponseDTOs;
using SCIQUSTICKETS.BUSINESS.BusinessModels.ResponseDTOs.AccountResponseDTOs;
using SCIQUSTICKETS.BUSINESS.Interfaces.IService;
using SCIQUSTICKETS.DATA.DomainModels;
using SCIQUSTICKETS.DATA.Interfaces.IRepositories;

namespace SCIQUSTICKETS.BUSINESS.Implementations.Service
{
    public class AccountService : IAccountService
    {
        private readonly IAccountRepository _accountRepository;

        public AccountService(IAccountRepository accountRepository)
        {
            _accountRepository = accountRepository;
        }

        public async Task<PagedResponse<AccountListResponse>> GetAllAccountsAsync(AccountQueryParams queryParams)
        {
            var (items, totalCount) = await _accountRepository.GetAllPagedAsync(
                queryParams.IsDeleted,
                queryParams.Search,
                queryParams.SortBy,
                queryParams.SortDescending,
                queryParams.Page,
                queryParams.PageSize);

            var listResponses = items.Select(a => new AccountListResponse
            {
                AccountId = a.AccountId,
                AutoGenerateAccountId = a.AutoGenerateAccountId,
                AccountName = a.AccountName,
                RegisteredMobileNumber = a.RegisteredMobileNumber,
                Email = a.Email,
                AccountProfileImg = a.AccountProfileImg,
                Status = a.Status,
                KeyAccount = a.KeyAccount,
                AccountTypeName = a.AccountTypes?.TypeName,
                IndustryTypeName = a.IndustryTypes?.Name,
                RegionName = a.Region?.Name,
                CreatedDate = a.CreatedDate
            }).ToList();

            return new PagedResponse<AccountListResponse>
            {
                Items = listResponses,
                TotalCount = totalCount,
                Page = queryParams.Page,
                PageSize = queryParams.PageSize
            };
        }

        public async Task<AccountResponse?> GetAccountByIdAsync(string accountId)
        {
            var account = await _accountRepository.GetWithDetailsByIdAsync(accountId);
            if (account == null) return null;

            return MapToResponse(account);
        }

        public async Task<AccountResponse> CreateAccountAsync(CreateAccountRequest request)
        {
            string autoGeneratedId = await _accountRepository.GenerateNextAccountIdAsync();

            var account = new Account
            {
                AutoGenerateAccountId = autoGeneratedId,
                AccountName = request.AccountName,
                RegisteredMobileNumber = request.RegisteredMobileNumber,
                SecondMobileNumber = request.SecondMobileNumber,
                Website = request.Website,
                Email = request.Email,
                AccountProfileImg = request.AccountProfileImg,
                IncorporationDate = request.IncorporationDate,
                AccountSince = request.AccountSince,
                EmployeeCount = request.EmployeeCount,
                KeyAccount = request.KeyAccount,
                CreatedByUserId = request.CreatedByUserId,
                AccountManagerId = request.AccountManagerId,
                CustomerSuccessManagerId = request.CustomerSuccessManagerId,
                AccountTypesId = request.AccountTypesId,
                IndustryTypeId = request.IndustryTypeId,
                RegionId = request.RegionId,
                CurrencyId = request.CurrencyId,
                DefaultCurrencySymbol = request.DefaultCurrencySymbol,
                ConvertCurrencySymbol = request.ConvertCurrencySymbol,
                ParentAccountId = request.ParentAccountId,
                ReferralAccountId = request.ReferralAccountId,
                ReferralAccountContactsId = request.ReferralAccountContactsId
            };

            await _accountRepository.AddAsync(account);
            await _accountRepository.SaveChangesAsync();

            var createdAccount = await _accountRepository.GetWithDetailsByIdAsync(account.AccountId);
            return MapToResponse(createdAccount ?? account);
        }

        public async Task<AccountResponse?> UpdateAccountAsync(string accountId, UpdateAccountRequest request)
        {
            var account = await _accountRepository.GetByIdAsync(accountId);
            if (account == null) return null;

            if (!string.IsNullOrEmpty(request.ParentAccountId) && request.ParentAccountId == accountId)
            {
                throw new InvalidOperationException("An account cannot be set as its own parent.");
            }

            account.AccountName = request.AccountName;
            account.RegisteredMobileNumber = request.RegisteredMobileNumber;
            account.SecondMobileNumber = request.SecondMobileNumber;
            account.Website = request.Website;
            account.Email = request.Email;
            account.AccountProfileImg = request.AccountProfileImg;
            account.Status = request.Status;
            account.IncorporationDate = request.IncorporationDate;
            account.AccountSince = request.AccountSince;
            account.EmployeeCount = request.EmployeeCount;
            account.KeyAccount = request.KeyAccount;
            account.AccountManagerId = request.AccountManagerId;
            account.CustomerSuccessManagerId = request.CustomerSuccessManagerId;
            account.AccountTypesId = request.AccountTypesId;
            account.IndustryTypeId = request.IndustryTypeId;
            account.RegionId = request.RegionId;
            account.CurrencyId = request.CurrencyId;
            account.DefaultCurrencySymbol = request.DefaultCurrencySymbol;
            account.ConvertCurrencySymbol = request.ConvertCurrencySymbol;
            account.ParentAccountId = request.ParentAccountId;
            account.ReferralAccountId = request.ReferralAccountId;
            account.LastUpdatedDate = DateTime.UtcNow;

            _accountRepository.Update(account);
            await _accountRepository.SaveChangesAsync();

            var updatedAccount = await _accountRepository.GetWithDetailsByIdAsync(accountId);
            return MapToResponse(updatedAccount ?? account);
        }

        public async Task<bool> SoftDeleteAccountAsync(string accountId)
        {
            return await _accountRepository.SoftDeleteAsync(accountId);
        }

        private static AccountResponse MapToResponse(Account a)
        {
            return new AccountResponse
            {
                AccountId = a.AccountId,
                AutoGenerateAccountId = a.AutoGenerateAccountId,
                AccountName = a.AccountName,
                RegisteredMobileNumber = a.RegisteredMobileNumber,
                SecondMobileNumber = a.SecondMobileNumber,
                Website = a.Website,
                Email = a.Email,
                AccountProfileImg = a.AccountProfileImg,
                Status = a.Status,
                IsDeleted = a.IsDeleted,
                CreatedDate = a.CreatedDate,
                LastUpdatedDate = a.LastUpdatedDate,
                IncorporationDate = a.IncorporationDate,
                AccountSince = a.AccountSince,
                EmployeeCount = a.EmployeeCount,
                KeyAccount = a.KeyAccount,
                CreatedByUserId = a.CreatedByUserId,
                CreatedByUserName = a.CreatedByUser?.Name,
                AccountManagerId = a.AccountManagerId,
                AccountManagerName = a.AccountManager?.Name,
                CustomerSuccessManagerId = a.CustomerSuccessManagerId,
                CustomerSuccessManagerName = a.CustomerSuccessManager?.Name,
                AccountTypesId = a.AccountTypesId,
                AccountTypeName = a.AccountTypes?.TypeName,
                IndustryTypeId = a.IndustryTypeId,
                IndustryTypeName = a.IndustryTypes?.Name,
                RegionId = a.RegionId,
                RegionName = a.Region?.Name,
                CurrencyId = a.CurrencyId,
                CurrencyCode = a.Currency?.CurrencyCode,
                DefaultCurrencySymbol = a.DefaultCurrencySymbol,
                ConvertCurrencySymbol = a.ConvertCurrencySymbol,
                ParentAccountId = a.ParentAccountId,
                ParentAccountName = a.ParentAccount?.AccountName,
                ReferralAccountId = a.ReferralAccountId,
                ReferralAccountName = a.ReferralAccount?.AccountName,
                ReferralAccountContactsId = a.ReferralAccountContactsId,
                ReferralAccountContactName = a.ReferralAccountContacts?.PersonName,
                Contacts = a.Contacts?.Select(c => new AccountContactResponse
                {
                    AccountContactsId = c.AccountContactsId,
                    PersonName = c.PersonName,
                    Designation = c.Designation,
                    Email = c.Email,
                    MobileNumber = c.MobileNumber,
                    AlternateMobileNumber = c.AlternateMobileNumber,
                    Department = c.Department,
                    Branch = c.Branch,
                    PrimaryContact = c.PrimaryContact,
                    ProfileImage = c.ProfileImage,
                    DOB = c.DOB,
                    Address = c.Address,
                    AssociatedSince = c.AssociatedSince,
                    AccountId = c.AccountId
                }).ToList() ?? new List<AccountContactResponse>(),
                Addresses = a.Addresses?.Select(ad => new AccountAddressResponse
                {
                    AccountAddressId = ad.AccountAddressId,
                    Country = ad.Country,
                    City = ad.City,
                    State = ad.State,
                    Pincode = ad.Pincode,
                    MapUrl = ad.MapUrl,
                    AddressLine = ad.AddressLine,
                    PrimaryAddress = ad.PrimaryAddress,
                    AccountId = ad.AccountId,
                    AddressTypes = ad.AddressTypes?.Select(at => at.TypeName).ToList() ?? new List<string>()
                }).ToList() ?? new List<AccountAddressResponse>()
            };
        }
    }
}
